import Head from 'next/head'
import { FC } from 'react'
import styles from '@/styles/PageWrapper.module.scss'
import Script from 'next/script'

type PropsType = {
  title?: string
  desc?: string
  children: JSX.Element | JSX.Element[]
  css?: string
  js?: string
}

/**
 * 通用页面模板
 * @param props 
 * @returns 
 */
const PageWrapper: FC<PropsType> = (props: PropsType) => {
  const {
    title = '问卷C端',
    desc = 'Generated by create next app',
    css = '',
    js = '',
    children
  } = props

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content={desc} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>{css}</style>
      </Head>
      <main className={styles.container}>{children}</main>
      <Script id="page-js">{js}</Script>
    </>
  )
}

export default PageWrapper
